title: Mikael Lundin Weblog
name: Mikael Lundin Weblog
description: Short stories about functional things, non-functional things, and things that doesn't function.
url: http://localhost:4000
markdown: redcarpet
redcarpet:
    extensions: ["tables"]
highligher: pygments
permalink: /:year/:month/:day/:title.html
google_analytics: UA-49087954-2

owner:
    name: Mikael Lundin
    disqus_shortname: tailcalloptimized
    twitter: mikaellundin

exclude: [bower_components/, node_modules/, package.json, gulpfile.js, rakefile.rb, s3_website.yml, bower.json, _src/]
